name:                day4
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - unordered-containers
  - hashable
  - split
  - text

executables:
  day4:
    source-dirs: src
    main:        Main.hs
