name:                day5
version:             0.1.0.0
synopsis:            Solution for Advent of Code
homepage:            http://adventofcode.com/2016
license:             BSD3
author:              Graham Enos

ghc-options: "-Wall -Werror -O2"

dependencies:
  - base >= 4.7 && < 5
  - array
  - bytestring
  - cryptonite

executables:
  day5:
    source-dirs:      src
    main:             Main.hs
