[package]
name = "day06"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
itertools = "0.13.0"
rayon = "1.10.0"

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
