name:                day12
version:             0.1.0.0
synopsis:            Solution for Advent of Code; see https://www.reddit.com/r/adventofcode/comments/5hus40/2016_day_12_solutions/db3z2ge/
homepage:            http://adventofcode.com/2016
license:             BSD3
author:              Graham Enos

ghc-options: "-Wall -Werror -O2"

dependencies:
  - base >= 4.7 && < 5
  - extra
  - file-embed
  - lens
  - megaparsec
  - transformers
  - text
  - vector

executables:
  day12:
    source-dirs:      src
    main:             Main.hs
