name:                day11
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - containers
  - linear
  - vector

executables:
  day11:
    source-dirs: src
    main:        Main.hs
