[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
fxhash = "0.2.1"
rayon = "1.10.0"

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
