name:                find-the-difference
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - containers

executables:
  find-the-difference:
    source-dirs: src
    main:        Main.hs
