name: isogram
version: 1.1.0.1

dependencies:
  - base

library:
  exposed-modules: Isogram
  source-dirs: src
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - isogram
      - hspec
