name: kindergarten-garden
version: 1.0.0.3

dependencies:
  - base

library:
  exposed-modules: Garden
  source-dirs: src
  dependencies:
    - containers
    - split

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - kindergarten-garden
      - hspec
