[package]
name = "day05"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.9"
itertools = "0.12.0"
peg = "0.8.2"
rayon = "1.8.0"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
