name: prime-factors
version: 1.0.0.3

dependencies:
  - base

library:
  exposed-modules: PrimeFactors
  source-dirs: src
  dependencies: []

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - prime-factors
      - hspec
