name:                day22
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base ^>= 4.12
  - groups ^>= 0.4.1.0
  - finite-typelits ^>= 0.1.4.2
  - text ^>= 1.2.3.1

executables:
  exe:
    source-dirs: src
    main:        Main.hs
