name:                day13
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - containers
  - monad-loops
  - mtl

executables:
  day13:
    source-dirs: src
    main:        Main.hs
