name:                day09
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - lens
  - pointedlist
  - vector
  - text

executables:
  day09:
    source-dirs: src
    main:        Main.hs
