name:                ppa
version:             0.1.0.0
synopsis:            TODO
description:         TODO
homepage:            https://github.com/genos/ppa#readme
license:             MIT
author:              Graham Enos
maintainer:          graham@quantifind.com
copyright:           Quantifind
category:            Math

ghc-options: -Wall -O2

default-extensions:
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5

executables:
  ppa:
    source-dirs: src
    main:        Main.hs
