name:                day3
license:             MIT

ghc-options: -Wall -Werror -O2

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - containers
  - text

executables:
  day3:
    source-dirs: src
    main:        Main.hs
