name:                day03
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base ^>= 4.12
  - containers ^>= 0.6.0.1
  - lens ^>= 4.17.1
  - linear ^>= 1.20.9
  - megaparsec ^>= 7.0.5
  - text ^>= 1.2.3.1

executables:
  exe:
    source-dirs: src
    main:        Main.hs
