name:                day03
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - containers
  - megaparsec
  - text

executables:
  day03:
    source-dirs: src
    main:        Main.hs
