name:                day03
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base ^>= 4.13
  - containers ^>= 0.6.0.1
  - lens ^>= 4.18.1
  - linear ^>= 1.20.9
  - megaparsec ^>= 8.0.0
  - text ^>= 1.2.3.1

executables:
  exe:
    source-dirs: src
    main:        Main.hs
