name: pascals-triangle
version: 1.2.0.5

dependencies:
  - base

library:
  exposed-modules: Triangle
  source-dirs: src
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pascals-triangle
      - hspec
