name:                day4
version:             0.1.0.0
synopsis:            Solution for Advent of Code
homepage:            http://adventofcode.com/2016
license:             BSD3
author:              Graham Enos

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - file-embed

executables:
  day4:
    source-dirs:      src
    main:             Main.hs
