name: secret-handshake
version: 1.1.0.4

dependencies:
  - base

library:
  exposed-modules: SecretHandshake
  source-dirs: src
  dependencies: []

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - secret-handshake
      - hspec
