name:                day8
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - lens
  - text

executables:
  day8:
    source-dirs: src
    main:        Main.hs
