name:                day06
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base ^>= 4.13
  - algebraic-graphs ^>= 0.5
  - containers ^>= 0.6.0.1
  - text ^>= 1.2.3.1

executables:
  exe:
    source-dirs: src
    main:        Main.hs
