name:                day08
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base ^>= 4.13
  - linear ^>= 1.20.9
  - text ^>= 1.2.3.1

executables:
  exe:
    source-dirs: src
    main:        Main.hs
