name:                day280
version:             0.1.0.0
synopsis:            TODO
description:         TODO
homepage:            https://github.com/genos/day280#readme
license:             MIT
author:              Graham Enos
maintainer:          graham.enos@gmail.com
copyright:           Graham Enos
category:            Math

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - primes

executables:
  day280:
    source-dirs: src
    main:        Main.hs
