name:                day02
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - text
  - vector

executables:
  exe:
    source-dirs: src
    main:        Main.hs
