name:                day02
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base ^>= 4.13
  - text ^>= 1.2.3.1
  - vector ^>= 0.12.0.3

executables:
  exe:
    source-dirs: src
    main:        Main.hs
