name:                day02
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base ^>= 4.13
  - text ^>= 1.2.4.0
  - vector ^>= 0.12.1.2

executables:
  exe:
    source-dirs: src
    main:        Main.hs
