name:                day08
license:             MIT

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - lens
  - text

executables:
  day08:
    source-dirs: src
    main:        Main.hs
