name: pangram
version: 1.1.0.3

dependencies:
  - base

library:
  exposed-modules: Pangram
  source-dirs: src
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pangram
      - hspec
